name: Train BitcoinHomeBroker LLM Model

on:
  push:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # (Opcional) Garante a pasta de modelos e baixa o último artifact, se existir
      - name: Prepare model dir
        run: mkdir -p outputs/model

      - name: Download previous model artifact (if any)
        uses: actions/download-artifact@v4
        with:
          name: bitcoinhomebroker.pth
          path: outputs/model
        continue-on-error: true

      - name: List files before install (debug)
        run: |
          pwd
          ls -lah
          ls -lah outputs || true
          ls -lah outputs/model || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python ml_advanced_integrated_FIXED.py

      # Normaliza o nome do arquivo caso o script salve com outro nome
      - name: Normalize model filename
        run: |
          if [ ! -f "outputs/model/bitcoinhomebroker.pth" ] && [ -f "bitcoinhomebroker.pth" ]; then
            mv btc_usdc_lstm_model_pytorch.pth outputs/model/bitcoinhomebroker.pth
          fi
          # Caso algum outro local/arquivo tenha sido usado, tente localizar e mover
          if [ ! -f "outputs/model/bitcoinhomebroker.pth" ]; then
            FOUND=$(find . -maxdepth 3 -type f -name "*.pth" | head -n 1 || true)
            if [ -n "$FOUND" ]; then
              mv "$FOUND" outputs/model/bitcoinhomebroker.pth
            fi
          fi
          ls -lah outputs/model || true

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: llm-model-BitcoinHomeBroker
          path: outputs/model/bitcoinhomebroker.pth
          if-no-files-found: error
